### ISSUE TITLE
`useAutosave` invokes callback function twice when `Editor` is mounted, wasting OpenAI credits when used with next@13.5.5|6

### ISSUE THREAD

**Issue by ppyrzanowski** [Hendrixer/fullstack-ai-nextjs#2]
Not a general Issue, here a head ups in case anyone wants to use a **newer Next.js version** than used in the course. 
Every time the `Editor` was mounted, the loading status would be visible for multiple seconds. This behavior was different to what was shown in the course. After some hours debugging for way too long, I encountered false behavior with the `useAutosave` hook from `react-autosave` package. `useAutosave` invokes its callback function `onSave` twice when `Editor` is mounted, as opposed to waiting for changes on its `data` property and then invoking the callback. Thus calling the PATCH endpoint twice on every `Editor` mount and wasting OpenAI credits.

The issue occurs when Next.js is bumped to 13.5.5 or 13.5.6.

**Comment by whovivekshukla** [comment]
Also, if you are on the free tier of OpenAI with 5 dollar worth of credits, you will get rate limit error.

**Comment by dtauer** [comment]
Thanks for catching this. I added an annotation to the course warning viewers of the increased API calls.
